# Generated by Django 3.0.5 on 2020-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200413_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
