# Generated by Django 3.0.5 on 2020-04-17 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_post', '0005_update_default_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailAddress',
            new_name='EmailAddress_post',
        ),
    ]
