# Generated by Django 3.0.3 on 2020-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource_type',
            field=models.CharField(choices=[('food', 'FOOD'), ('clothes', 'CLOTHES'), ('books', 'BOOKS')], default='food', max_length=7),
        ),
    ]
