# Generated by Django 3.0.3 on 2020-03-10 11:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_task_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
