# Generated by Django 3.0.3 on 2020-03-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200310_1745'),
        ('blog', '0005_auto_20200310_1700'),
    ]

    operations = [
    ]
